### ISSUE TITLE
How Print the label of test sample?

### ISSUE THREAD

**Issue by alighofrani95** [shashankvkt/AnomalyDetection_UCF_Crime#1]
thanks a lot for sharing project,
prediction.shape returns [32,1] I can't understand It's meaning.

the ucf-crime dataset has 14class (13 abnormal + 1 normal) how it became to 32???
and finaly how can i find the estimated label of test video?

**Comment by ptirupat** [comment]
The output is not a label for the whole video it is per-frame anomaly score [0 1]. In this work we are not detecting the class of anomaly, the prediction is a binary prediction indicating the presence or absence of anomaly. Please refer to the paper to see how the features from the video are grouped into 32 bags.
