### ISSUE TITLE
 No such file: trained_models/flownets_EPE1.951.pth.tar

### ISSUE THREAD

**Issue by Jimjipeng** [shashankvkt/AnomalyDetection_UCF_Crime#2]
flownet_model = './trained_models/flownets_EPE1.951.pth.tar'
i3d_model_flow = './trained_models/flow_charades.pt'
i3d_model_rgb = './trained_models/rgb_charades.pt'
Where can these files be downloaded?

**Comment by shashankvkt** [comment]
Hi,
you can download it from https://github.com/piergiaj/pytorch-i3d
